name: CI deployback-db
    on:
       push:
          branch:
            - main
          pull_request:


jobs:
    build-and-test:
        runs-on: ubuntu-latest
          steps:
            - name: Check source code
              uses: actions/checkout@v3
              
            - name: run compose
              run: |
                  docker compose up -d
                  echo "running compose..."
                  sleep 20
            - name: run test web
              run: docker compose exec -it web curl http://localhost:5000/api/users
            - name: shut down compose
               if: always()
              run: docker compose down
